Styling adjustments
CaptainCoderOrg/TacticsEngine pull request #50
Opened 2024-05-06 20:20 UTC by JanluOfficial

### Changes
- Added a red glow on `.invalid-position`
- Fixed positioning of `.dragged-element` and `.invalid-position`
- Disabled text selection on `h2` in FigurePanel to prevent unintended behavior in Microsoft Edge

2024-05-06 20:23 UTC, JanluOfficial commented
I have no idea why the `comment-report` check was not successful.

2024-05-06 20:31 UTC, JanluOfficial commented
Maybe because I merged in main from the repo

2024-05-07 16:49 UTC, jcollard requested changes
Thanks for the PR. I've left some comments for you.

2024-05-07 16:49 UTC, jcollard commented on WebEditor/Components/Board/ElementRenderer.razor.css
> +    margin: -2px -2px;
I believe this should be `-var(--figure-margin)` rather than hard coded at 2px.

2024-05-07 16:49 UTC, jcollard commented on WebEditor/Components/Panels/FigurePanel.razor.css
> +    user-select: none;
I've added `user-select: none` to the entire set of panels in the latest update to `main`. I've also updated #40 to reflect that I want to be able to highlight some text when not dragging.

2024-05-20 15:21 UTC, closed without merging