feat: allow user defined figures
CaptainCoderOrg/TacticsEngine pull request #82
Opened 2024-05-16 11:55 UTC by solomoncyj

2024-05-16 11:59 UTC, viceroypenguin commented on WebEditor/Components/Panels/FigurePanel.razor
> +    private void AddNewFigure{
syntax error - should be `private void AddNewFigure() {`

2024-05-17 13:42 UTC, jcollard commented
@solomoncyj Thanks for your PR. It will be great to have this as a feature! However, I'm having some trouble getting your branch to run. This is what I'm seeing when I check out your branch:

![image](https://github.com/CaptainCoderOrg/TacticsEngine/assets/3529380/38c941dd-67f8-4d57-9169-12127a902eab)

2024-05-17 13:45 UTC, jcollard requested changes

2024-05-17 13:45 UTC, jcollard commented on WebEditor/Components/Panels/FigurePanel.razor
> +    <input type="text" placeholder="Width" @bind="@NewWidth" />
I think we should use an `<InputNumber>` rather than a raw HTML input. See: https://learn.microsoft.com/en-us/aspnet/core/blazor/forms/input-components?view=aspnetcore-8.0

Doing this, you can bind directly to an integer and avoid the parsing in `AddNewFigure`

2024-05-17 16:14 UTC, solomoncyj commented
@jcollard opps, i for got commit my changes. the bug should be fixed. i am now working on numeric input

2024-05-17 16:26 UTC, solomoncyj commented
@jcollard opps, i for got commit my changes. the bug should be fixed.

2024-05-18 15:10 UTC, jcollard approved these changes
Looks good! Thanks!

2024-05-18 15:10 UTC, merged